services:
  db:
    image: mysql:5.7
    container_name: gestion_salas_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_salas
      MYSQL_USER: gestion_salas_user
      MYSQL_PASSWORD: shaw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  api:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: gestion_salas

      # Todos los roles, mismos credenciales:
      DB_USER_INVITED: gestion_salas_user
      DB_PASSWORD_INVITED: shaw

      DB_USER_USER: gestion_salas_Usuario
      DB_PASSWORD_USER: shaw

      DB_USER_BIBLIO: gestion_salas_Bibliotecario
      DB_PASSWORD_BIBLIO: shaw

      DB_USER_ADMIN: gestion_salas_Administrador
      DB_PASSWORD_ADMIN: shaw


    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./FastAPI:/code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: gestion_salas_frontend
    ports:
      - "5173:5173"   
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mysql_data:
